name: macOS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macOS-Xcode:
    name: macOS Xcode
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [12.3, 11.7, 10.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake
        run: cmake -S test -B build -DCMAKE_BUILD_TYPE="Release"
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --verbose
